version: '3'
services:
  # Backend
  backend:
    build: .
    container_name: backend
    ports:
      - "5001:5000"
    networks:
      - webapp_network
    depends_on:
      - database

  # Frontend
  frontend:
    image: node:latest
    container_name: frontend
    working_dir: /app
    volumes:
      - ./meu_projeto:/app  # Update volume mapping to include entire project directory
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - webapp_network

  # Database (MySQL)
  database:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 456123
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: Vlap
      MYSQL_PASSWORD: 456123
    ports:
      - "3306:3306"
    networks:
      - webapp_network

networks:
  webapp_network:
    driver: bridge
